FROM node:20-alpine

RUN apk add --no-cache libc6-compat netcat-openbsd

WORKDIR /app

COPY backend/package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm install

COPY backend/ .

COPY docker/backend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/entrypoint.sh"]
CMD ["npm", "run", "start:dev"]
